# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/tape_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/lab/api/tape_service.proto',
  package='chromiumos.test.lab.api',
  syntax='proto3',
  serialized_options=b'Z1go.chromium.org/chromiumos/config/go/test/lab/api',
  serialized_pb=b'\n*chromiumos/test/lab/api/tape_service.proto\x12\x17\x63hromiumos.test.lab.api\"s\n\x0f\x43\x61llTapeRequest\x12\x18\n\x10request_endpoint\x18\x01 \x01(\t\x12\x16\n\x0erequest_method\x18\x02 \x01(\t\x12\x17\n\x0frequest_timeout\x18\x03 \x01(\x05\x12\x15\n\rpayload_bytes\x18\x04 \x01(\x0c\")\n\x10\x43\x61llTapeResponse\x12\x15\n\rpayload_bytes\x18\x01 \x01(\x0c\x32n\n\x0bTapeService\x12_\n\x08\x43\x61llTape\x12(.chromiumos.test.lab.api.CallTapeRequest\x1a).chromiumos.test.lab.api.CallTapeResponseB3Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3'
)




_CALLTAPEREQUEST = _descriptor.Descriptor(
  name='CallTapeRequest',
  full_name='chromiumos.test.lab.api.CallTapeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_endpoint', full_name='chromiumos.test.lab.api.CallTapeRequest.request_endpoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_method', full_name='chromiumos.test.lab.api.CallTapeRequest.request_method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_timeout', full_name='chromiumos.test.lab.api.CallTapeRequest.request_timeout', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_bytes', full_name='chromiumos.test.lab.api.CallTapeRequest.payload_bytes', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=186,
)


_CALLTAPERESPONSE = _descriptor.Descriptor(
  name='CallTapeResponse',
  full_name='chromiumos.test.lab.api.CallTapeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_bytes', full_name='chromiumos.test.lab.api.CallTapeResponse.payload_bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['CallTapeRequest'] = _CALLTAPEREQUEST
DESCRIPTOR.message_types_by_name['CallTapeResponse'] = _CALLTAPERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallTapeRequest = _reflection.GeneratedProtocolMessageType('CallTapeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALLTAPEREQUEST,
  '__module__' : 'chromiumos.test.lab.api.tape_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.lab.api.CallTapeRequest)
  })
_sym_db.RegisterMessage(CallTapeRequest)

CallTapeResponse = _reflection.GeneratedProtocolMessageType('CallTapeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLTAPERESPONSE,
  '__module__' : 'chromiumos.test.lab.api.tape_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.lab.api.CallTapeResponse)
  })
_sym_db.RegisterMessage(CallTapeResponse)


DESCRIPTOR._options = None

_TAPESERVICE = _descriptor.ServiceDescriptor(
  name='TapeService',
  full_name='chromiumos.test.lab.api.TapeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=231,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallTape',
    full_name='chromiumos.test.lab.api.TapeService.CallTape',
    index=0,
    containing_service=None,
    input_type=_CALLTAPEREQUEST,
    output_type=_CALLTAPERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAPESERVICE)

DESCRIPTOR.services_by_name['TapeService'] = _TAPESERVICE

# @@protoc_insertion_point(module_scope)
