# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/usb_drive.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/lab/api/usb_drive.proto',
  package='chromiumos.test.lab.api',
  syntax='proto3',
  serialized_options=b'Z1go.chromium.org/chromiumos/config/go/test/lab/api',
  serialized_pb=b'\n\'chromiumos/test/lab/api/usb_drive.proto\x12\x17\x63hromiumos.test.lab.api\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n\x08UsbDrive\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x02 \x01(\t\x12\x33\n\x0f\x66irst_seen_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB3Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_USBDRIVE = _descriptor.Descriptor(
  name='UsbDrive',
  full_name='chromiumos.test.lab.api.UsbDrive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial', full_name='chromiumos.test.lab.api.UsbDrive.serial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='chromiumos.test.lab.api.UsbDrive.manufacturer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_seen_time', full_name='chromiumos.test.lab.api.UsbDrive.first_seen_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=202,
)

_USBDRIVE.fields_by_name['first_seen_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UsbDrive'] = _USBDRIVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UsbDrive = _reflection.GeneratedProtocolMessageType('UsbDrive', (_message.Message,), {
  'DESCRIPTOR' : _USBDRIVE,
  '__module__' : 'chromiumos.test.lab.api.usb_drive_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.lab.api.UsbDrive)
  })
_sym_db.RegisterMessage(UsbDrive)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
