# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/artifact/test_plan.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api.v1 import plan_pb2 as chromiumos_dot_test_dot_api_dot_v1_dot_plan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/artifact/test_plan.proto',
  package='chromiumos.test.artifact',
  syntax='proto3',
  serialized_options=b'Z2go.chromium.org/chromiumos/config/go/test/artifact',
  serialized_pb=b'\n(chromiumos/test/artifact/test_plan.proto\x12\x18\x63hromiumos.test.artifact\x1a!chromiumos/test/api/v1/plan.proto\"M\n\x10TestPlanArtifact\x12\x39\n\rhw_test_plans\x18\x01 \x03(\x0b\x32\".chromiumos.test.api.v1.HWTestPlanB4Z2go.chromium.org/chromiumos/config/go/test/artifactb\x06proto3'
  ,
  dependencies=[chromiumos_dot_test_dot_api_dot_v1_dot_plan__pb2.DESCRIPTOR,])




_TESTPLANARTIFACT = _descriptor.Descriptor(
  name='TestPlanArtifact',
  full_name='chromiumos.test.artifact.TestPlanArtifact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hw_test_plans', full_name='chromiumos.test.artifact.TestPlanArtifact.hw_test_plans', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=182,
)

_TESTPLANARTIFACT.fields_by_name['hw_test_plans'].message_type = chromiumos_dot_test_dot_api_dot_v1_dot_plan__pb2._HWTESTPLAN
DESCRIPTOR.message_types_by_name['TestPlanArtifact'] = _TESTPLANARTIFACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestPlanArtifact = _reflection.GeneratedProtocolMessageType('TestPlanArtifact', (_message.Message,), {
  'DESCRIPTOR' : _TESTPLANARTIFACT,
  '__module__' : 'chromiumos.test.artifact.test_plan_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.artifact.TestPlanArtifact)
  })
_sym_db.RegisterMessage(TestPlanArtifact)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
