# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/steps/enumeration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import test_metadata_pb2 as chromite_dot_api_dot_test__metadata__pb2
from chromite.api.gen_sdk.test_platform import request_pb2 as test__platform_dot_request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%test_platform/steps/enumeration.proto\x12\x13test_platform.steps\x1a chromite/api/test_metadata.proto\x1a\x1btest_platform/request.proto\"\x87\x02\n\x13\x45numerationRequests\x12\x39\n\x08requests\x18\x01 \x03(\x0b\x32\'.test_platform.steps.EnumerationRequest\x12U\n\x0ftagged_requests\x18\x02 \x03(\x0b\x32<.test_platform.steps.EnumerationRequests.TaggedRequestsEntry\x1a^\n\x13TaggedRequestsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.test_platform.steps.EnumerationRequest:\x02\x38\x01\"\x8f\x02\n\x14\x45numerationResponses\x12;\n\tresponses\x18\x01 \x03(\x0b\x32(.test_platform.steps.EnumerationResponse\x12X\n\x10tagged_responses\x18\x02 \x03(\x0b\x32>.test_platform.steps.EnumerationResponses.TaggedResponsesEntry\x1a`\n\x14TaggedResponsesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.test_platform.steps.EnumerationResponse:\x02\x38\x01\"\x82\x01\n\x12\x45numerationRequest\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.test_platform.Request.Params.Metadata\x12\x32\n\ttest_plan\x18\x04 \x01(\x0b\x32\x1f.test_platform.Request.TestPlan\"\x8f\x03\n\x13\x45numerationResponse\x12Y\n\x14\x61utotest_invocations\x18\x02 \x03(\x0b\x32;.test_platform.steps.EnumerationResponse.AutotestInvocation\x12\x15\n\rerror_summary\x18\x03 \x01(\t\x1a\x85\x02\n\x12\x41utotestInvocation\x12(\n\x04test\x18\x01 \x01(\x0b\x32\x1a.chromite.api.AutotestTest\x12\x11\n\ttest_args\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x66\n\x0eresult_keyvals\x18\x04 \x03(\x0b\x32N.test_platform.steps.EnumerationResponse.AutotestInvocation.ResultKeyvalsEntry\x1a\x34\n\x12ResultKeyvalsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42?Z=go.chromium.org/chromiumos/infra/proto/go/test_platform/stepsb\x06proto3')



_ENUMERATIONREQUESTS = DESCRIPTOR.message_types_by_name['EnumerationRequests']
_ENUMERATIONREQUESTS_TAGGEDREQUESTSENTRY = _ENUMERATIONREQUESTS.nested_types_by_name['TaggedRequestsEntry']
_ENUMERATIONRESPONSES = DESCRIPTOR.message_types_by_name['EnumerationResponses']
_ENUMERATIONRESPONSES_TAGGEDRESPONSESENTRY = _ENUMERATIONRESPONSES.nested_types_by_name['TaggedResponsesEntry']
_ENUMERATIONREQUEST = DESCRIPTOR.message_types_by_name['EnumerationRequest']
_ENUMERATIONRESPONSE = DESCRIPTOR.message_types_by_name['EnumerationResponse']
_ENUMERATIONRESPONSE_AUTOTESTINVOCATION = _ENUMERATIONRESPONSE.nested_types_by_name['AutotestInvocation']
_ENUMERATIONRESPONSE_AUTOTESTINVOCATION_RESULTKEYVALSENTRY = _ENUMERATIONRESPONSE_AUTOTESTINVOCATION.nested_types_by_name['ResultKeyvalsEntry']
EnumerationRequests = _reflection.GeneratedProtocolMessageType('EnumerationRequests', (_message.Message,), {

  'TaggedRequestsEntry' : _reflection.GeneratedProtocolMessageType('TaggedRequestsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ENUMERATIONREQUESTS_TAGGEDREQUESTSENTRY,
    '__module__' : 'test_platform.steps.enumeration_pb2'
    # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationRequests.TaggedRequestsEntry)
    })
  ,
  'DESCRIPTOR' : _ENUMERATIONREQUESTS,
  '__module__' : 'test_platform.steps.enumeration_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationRequests)
  })
_sym_db.RegisterMessage(EnumerationRequests)
_sym_db.RegisterMessage(EnumerationRequests.TaggedRequestsEntry)

EnumerationResponses = _reflection.GeneratedProtocolMessageType('EnumerationResponses', (_message.Message,), {

  'TaggedResponsesEntry' : _reflection.GeneratedProtocolMessageType('TaggedResponsesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ENUMERATIONRESPONSES_TAGGEDRESPONSESENTRY,
    '__module__' : 'test_platform.steps.enumeration_pb2'
    # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationResponses.TaggedResponsesEntry)
    })
  ,
  'DESCRIPTOR' : _ENUMERATIONRESPONSES,
  '__module__' : 'test_platform.steps.enumeration_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationResponses)
  })
_sym_db.RegisterMessage(EnumerationResponses)
_sym_db.RegisterMessage(EnumerationResponses.TaggedResponsesEntry)

EnumerationRequest = _reflection.GeneratedProtocolMessageType('EnumerationRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENUMERATIONREQUEST,
  '__module__' : 'test_platform.steps.enumeration_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationRequest)
  })
_sym_db.RegisterMessage(EnumerationRequest)

EnumerationResponse = _reflection.GeneratedProtocolMessageType('EnumerationResponse', (_message.Message,), {

  'AutotestInvocation' : _reflection.GeneratedProtocolMessageType('AutotestInvocation', (_message.Message,), {

    'ResultKeyvalsEntry' : _reflection.GeneratedProtocolMessageType('ResultKeyvalsEntry', (_message.Message,), {
      'DESCRIPTOR' : _ENUMERATIONRESPONSE_AUTOTESTINVOCATION_RESULTKEYVALSENTRY,
      '__module__' : 'test_platform.steps.enumeration_pb2'
      # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationResponse.AutotestInvocation.ResultKeyvalsEntry)
      })
    ,
    'DESCRIPTOR' : _ENUMERATIONRESPONSE_AUTOTESTINVOCATION,
    '__module__' : 'test_platform.steps.enumeration_pb2'
    # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationResponse.AutotestInvocation)
    })
  ,
  'DESCRIPTOR' : _ENUMERATIONRESPONSE,
  '__module__' : 'test_platform.steps.enumeration_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.steps.EnumerationResponse)
  })
_sym_db.RegisterMessage(EnumerationResponse)
_sym_db.RegisterMessage(EnumerationResponse.AutotestInvocation)
_sym_db.RegisterMessage(EnumerationResponse.AutotestInvocation.ResultKeyvalsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z=go.chromium.org/chromiumos/infra/proto/go/test_platform/steps'
  _ENUMERATIONREQUESTS_TAGGEDREQUESTSENTRY._options = None
  _ENUMERATIONREQUESTS_TAGGEDREQUESTSENTRY._serialized_options = b'8\001'
  _ENUMERATIONRESPONSES_TAGGEDRESPONSESENTRY._options = None
  _ENUMERATIONRESPONSES_TAGGEDRESPONSESENTRY._serialized_options = b'8\001'
  _ENUMERATIONRESPONSE_AUTOTESTINVOCATION_RESULTKEYVALSENTRY._options = None
  _ENUMERATIONRESPONSE_AUTOTESTINVOCATION_RESULTKEYVALSENTRY._serialized_options = b'8\001'
  _ENUMERATIONREQUESTS._serialized_start=126
  _ENUMERATIONREQUESTS._serialized_end=389
  _ENUMERATIONREQUESTS_TAGGEDREQUESTSENTRY._serialized_start=295
  _ENUMERATIONREQUESTS_TAGGEDREQUESTSENTRY._serialized_end=389
  _ENUMERATIONRESPONSES._serialized_start=392
  _ENUMERATIONRESPONSES._serialized_end=663
  _ENUMERATIONRESPONSES_TAGGEDRESPONSESENTRY._serialized_start=567
  _ENUMERATIONRESPONSES_TAGGEDRESPONSESENTRY._serialized_end=663
  _ENUMERATIONREQUEST._serialized_start=666
  _ENUMERATIONREQUEST._serialized_end=796
  _ENUMERATIONRESPONSE._serialized_start=799
  _ENUMERATIONRESPONSE._serialized_end=1198
  _ENUMERATIONRESPONSE_AUTOTESTINVOCATION._serialized_start=937
  _ENUMERATIONRESPONSE_AUTOTESTINVOCATION._serialized_end=1198
  _ENUMERATIONRESPONSE_AUTOTESTINVOCATION_RESULTKEYVALSENTRY._serialized_start=1146
  _ENUMERATIONRESPONSE_AUTOTESTINVOCATION_RESULTKEYVALSENTRY._serialized_end=1198
# @@protoc_insertion_point(module_scope)
