# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/autotest/dynamic_suite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import test_metadata_pb2 as chromite_dot_api_dot_test__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*test_platform/autotest/dynamic_suite.proto\x12\x16test_platform.autotest\x1a chromite/api/test_metadata.proto\"=\n\x10TestPlatformArgs\x12)\n\x05tests\x18\x01 \x03(\x0b\x32\x1a.chromite.api.AutotestTestBBZ@go.chromium.org/chromiumos/infra/proto/go/test_platform/autotestb\x06proto3')



_TESTPLATFORMARGS = DESCRIPTOR.message_types_by_name['TestPlatformArgs']
TestPlatformArgs = _reflection.GeneratedProtocolMessageType('TestPlatformArgs', (_message.Message,), {
  'DESCRIPTOR' : _TESTPLATFORMARGS,
  '__module__' : 'test_platform.autotest.dynamic_suite_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.autotest.TestPlatformArgs)
  })
_sym_db.RegisterMessage(TestPlatformArgs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z@go.chromium.org/chromiumos/infra/proto/go/test_platform/autotest'
  _TESTPLATFORMARGS._serialized_start=104
  _TESTPLATFORMARGS._serialized_end=165
# @@protoc_insertion_point(module_scope)
