# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/skylab_test_runner/cft_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from chromite.api.gen_sdk.test_platform import request_pb2 as test__platform_dot_request__pb2
from chromite.api.gen_sdk.chromiumos.test.api import provision_state_pb2 as chromiumos_dot_test_dot_api_dot_provision__state__pb2
from chromite.api.gen_sdk.chromiumos.test.api import test_suite_pb2 as chromiumos_dot_test_dot_api_dot_test__suite__pb2
from chromite.api.gen_sdk.chromiumos.test.lab.api import dut_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_dut__pb2
from chromite.api.gen_sdk.chromiumos.build.api import container_metadata_pb2 as chromiumos_dot_build_dot_api_dot_container__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2test_platform/skylab_test_runner/cft_request.proto\x12 test_platform.skylab_test_runner\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1btest_platform/request.proto\x1a)chromiumos/test/api/provision_state.proto\x1a$chromiumos/test/api/test_suite.proto\x1a!chromiumos/test/lab/api/dut.proto\x1a-chromiumos/build/api/container_metadata.proto\"\xa2\x06\n\x0e\x43\x46TTestRequest\x12L\n\x0bprimary_dut\x18\x01 \x01(\x0b\x32\x37.test_platform.skylab_test_runner.CFTTestRequest.Device\x12O\n\x0e\x63ompanion_duts\x18\x02 \x03(\x0b\x32\x37.test_platform.skylab_test_runner.CFTTestRequest.Device\x12\x33\n\x0btest_suites\x18\x03 \x03(\x0b\x32\x1e.chromiumos.test.api.TestSuite\x12,\n\x08\x64\x65\x61\x64line\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1a\n\x12parent_request_uid\x18\x05 \x01(\t\x12\x17\n\x0fparent_build_id\x18\x06 \x01(\x03\x12_\n\x10\x61utotest_keyvals\x18\x07 \x03(\x0b\x32\x45.test_platform.skylab_test_runner.CFTTestRequest.AutotestKeyvalsEntry\x12\\\n\x1f\x64\x65\x66\x61ult_test_execution_behavior\x18\x08 \x01(\x0e\x32\x33.test_platform.Request.Params.TestExecutionBehavior\x12\x43\n\x12\x63ontainer_metadata\x18\t \x01(\x0b\x32\'.chromiumos.build.api.ContainerMetadata\x1a\x36\n\x14\x41utotestKeyvalsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x9c\x01\n\x06\x44\x65vice\x12\x34\n\tdut_model\x18\x01 \x01(\x0b\x32!.chromiumos.test.lab.api.DutModel\x12<\n\x0fprovision_state\x18\x02 \x01(\x0b\x32#.chromiumos.test.api.ProvisionState\x12\x1e\n\x16\x63ontainer_metadata_key\x18\x03 \x01(\tBLZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_test_runnerb\x06proto3')



_CFTTESTREQUEST = DESCRIPTOR.message_types_by_name['CFTTestRequest']
_CFTTESTREQUEST_AUTOTESTKEYVALSENTRY = _CFTTESTREQUEST.nested_types_by_name['AutotestKeyvalsEntry']
_CFTTESTREQUEST_DEVICE = _CFTTESTREQUEST.nested_types_by_name['Device']
CFTTestRequest = _reflection.GeneratedProtocolMessageType('CFTTestRequest', (_message.Message,), {

  'AutotestKeyvalsEntry' : _reflection.GeneratedProtocolMessageType('AutotestKeyvalsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CFTTESTREQUEST_AUTOTESTKEYVALSENTRY,
    '__module__' : 'test_platform.skylab_test_runner.cft_request_pb2'
    # @@protoc_insertion_point(class_scope:test_platform.skylab_test_runner.CFTTestRequest.AutotestKeyvalsEntry)
    })
  ,

  'Device' : _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
    'DESCRIPTOR' : _CFTTESTREQUEST_DEVICE,
    '__module__' : 'test_platform.skylab_test_runner.cft_request_pb2'
    # @@protoc_insertion_point(class_scope:test_platform.skylab_test_runner.CFTTestRequest.Device)
    })
  ,
  'DESCRIPTOR' : _CFTTESTREQUEST,
  '__module__' : 'test_platform.skylab_test_runner.cft_request_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.skylab_test_runner.CFTTestRequest)
  })
_sym_db.RegisterMessage(CFTTestRequest)
_sym_db.RegisterMessage(CFTTestRequest.AutotestKeyvalsEntry)
_sym_db.RegisterMessage(CFTTestRequest.Device)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_test_runner'
  _CFTTESTREQUEST_AUTOTESTKEYVALSENTRY._options = None
  _CFTTESTREQUEST_AUTOTESTKEYVALSENTRY._serialized_options = b'8\001'
  _CFTTESTREQUEST._serialized_start=314
  _CFTTESTREQUEST._serialized_end=1116
  _CFTTESTREQUEST_AUTOTESTKEYVALSENTRY._serialized_start=903
  _CFTTESTREQUEST_AUTOTESTKEYVALSENTRY._serialized_end=957
  _CFTTESTREQUEST_DEVICE._serialized_start=960
  _CFTTESTREQUEST_DEVICE._serialized_end=1116
# @@protoc_insertion_point(module_scope)
