# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/public_replication/public_replication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=chromiumos/config/public_replication/public_replication.proto\x12$chromiumos.config.public_replication\x1a google/protobuf/field_mask.proto\"F\n\x11PublicReplication\x12\x31\n\rpublic_fields\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.FieldMaskB9Z7go.chromium.org/chromiumos/config/go/public_replicationb\x06proto3')



_PUBLICREPLICATION = DESCRIPTOR.message_types_by_name['PublicReplication']
PublicReplication = _reflection.GeneratedProtocolMessageType('PublicReplication', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICREPLICATION,
  '__module__' : 'chromiumos.config.public_replication.public_replication_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.public_replication.PublicReplication)
  })
_sym_db.RegisterMessage(PublicReplication)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7go.chromium.org/chromiumos/config/go/public_replication'
  _PUBLICREPLICATION._serialized_start=137
  _PUBLICREPLICATION._serialized_end=207
# @@protoc_insertion_point(module_scope)
