# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63hromite/api/api.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\"\x15\n\x13\x43ompileProtoRequest\"w\n\x14\x43ompileProtoResponse\x12\x44\n\x0emodified_files\x18\x01 \x03(\x0b\x32,.chromite.api.CompileProtoResponse.ProtoFile\x1a\x19\n\tProtoFile\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x12\n\x10MethodGetRequest\"f\n\x11MethodGetResponse\x12\x37\n\x07methods\x18\x01 \x03(\x0b\x32&.chromite.api.MethodGetResponse.Method\x1a\x18\n\x06Method\x12\x0e\n\x06method\x18\x01 \x01(\t\"\x13\n\x11VersionGetRequest\"\x85\x01\n\x12VersionGetResponse\x12\x39\n\x07version\x18\x01 \x01(\x0b\x32(.chromite.api.VersionGetResponse.Version\x1a\x34\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\x0b\n\x03\x62ug\x18\x03 \x01(\x05\x32p\n\nApiService\x12U\n\x0c\x43ompileProto\x12!.chromite.api.CompileProtoRequest\x1a\".chromite.api.CompileProtoResponse\x1a\x0b\xc2\xed\x1a\x07\n\x03\x61pi\x10\x02\x32v\n\rMethodService\x12X\n\x03Get\x12\x1e.chromite.api.MethodGetRequest\x1a\x1f.chromite.api.MethodGetResponse\"\x10\xc2\xed\x1a\x0c\n\nGetMethods\x1a\x0b\xc2\xed\x1a\x07\n\x03\x61pi\x10\x02\x32y\n\x0eVersionService\x12Z\n\x03Get\x12\x1f.chromite.api.VersionGetRequest\x1a .chromite.api.VersionGetResponse\"\x10\xc2\xed\x1a\x0c\n\nGetVersion\x1a\x0b\xc2\xed\x1a\x07\n\x03\x61pi\x10\x02\x42\x38Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3')



_COMPILEPROTOREQUEST = DESCRIPTOR.message_types_by_name['CompileProtoRequest']
_COMPILEPROTORESPONSE = DESCRIPTOR.message_types_by_name['CompileProtoResponse']
_COMPILEPROTORESPONSE_PROTOFILE = _COMPILEPROTORESPONSE.nested_types_by_name['ProtoFile']
_METHODGETREQUEST = DESCRIPTOR.message_types_by_name['MethodGetRequest']
_METHODGETRESPONSE = DESCRIPTOR.message_types_by_name['MethodGetResponse']
_METHODGETRESPONSE_METHOD = _METHODGETRESPONSE.nested_types_by_name['Method']
_VERSIONGETREQUEST = DESCRIPTOR.message_types_by_name['VersionGetRequest']
_VERSIONGETRESPONSE = DESCRIPTOR.message_types_by_name['VersionGetResponse']
_VERSIONGETRESPONSE_VERSION = _VERSIONGETRESPONSE.nested_types_by_name['Version']
CompileProtoRequest = _reflection.GeneratedProtocolMessageType('CompileProtoRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPILEPROTOREQUEST,
  '__module__' : 'chromite.api.api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.CompileProtoRequest)
  })
_sym_db.RegisterMessage(CompileProtoRequest)

CompileProtoResponse = _reflection.GeneratedProtocolMessageType('CompileProtoResponse', (_message.Message,), {

  'ProtoFile' : _reflection.GeneratedProtocolMessageType('ProtoFile', (_message.Message,), {
    'DESCRIPTOR' : _COMPILEPROTORESPONSE_PROTOFILE,
    '__module__' : 'chromite.api.api_pb2'
    # @@protoc_insertion_point(class_scope:chromite.api.CompileProtoResponse.ProtoFile)
    })
  ,
  'DESCRIPTOR' : _COMPILEPROTORESPONSE,
  '__module__' : 'chromite.api.api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.CompileProtoResponse)
  })
_sym_db.RegisterMessage(CompileProtoResponse)
_sym_db.RegisterMessage(CompileProtoResponse.ProtoFile)

MethodGetRequest = _reflection.GeneratedProtocolMessageType('MethodGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _METHODGETREQUEST,
  '__module__' : 'chromite.api.api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.MethodGetRequest)
  })
_sym_db.RegisterMessage(MethodGetRequest)

MethodGetResponse = _reflection.GeneratedProtocolMessageType('MethodGetResponse', (_message.Message,), {

  'Method' : _reflection.GeneratedProtocolMessageType('Method', (_message.Message,), {
    'DESCRIPTOR' : _METHODGETRESPONSE_METHOD,
    '__module__' : 'chromite.api.api_pb2'
    # @@protoc_insertion_point(class_scope:chromite.api.MethodGetResponse.Method)
    })
  ,
  'DESCRIPTOR' : _METHODGETRESPONSE,
  '__module__' : 'chromite.api.api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.MethodGetResponse)
  })
_sym_db.RegisterMessage(MethodGetResponse)
_sym_db.RegisterMessage(MethodGetResponse.Method)

VersionGetRequest = _reflection.GeneratedProtocolMessageType('VersionGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONGETREQUEST,
  '__module__' : 'chromite.api.api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.VersionGetRequest)
  })
_sym_db.RegisterMessage(VersionGetRequest)

VersionGetResponse = _reflection.GeneratedProtocolMessageType('VersionGetResponse', (_message.Message,), {

  'Version' : _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {
    'DESCRIPTOR' : _VERSIONGETRESPONSE_VERSION,
    '__module__' : 'chromite.api.api_pb2'
    # @@protoc_insertion_point(class_scope:chromite.api.VersionGetResponse.Version)
    })
  ,
  'DESCRIPTOR' : _VERSIONGETRESPONSE,
  '__module__' : 'chromite.api.api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.VersionGetResponse)
  })
_sym_db.RegisterMessage(VersionGetResponse)
_sym_db.RegisterMessage(VersionGetResponse.Version)

_APISERVICE = DESCRIPTOR.services_by_name['ApiService']
_METHODSERVICE = DESCRIPTOR.services_by_name['MethodService']
_VERSIONSERVICE = DESCRIPTOR.services_by_name['VersionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api'
  _APISERVICE._options = None
  _APISERVICE._serialized_options = b'\302\355\032\007\n\003api\020\002'
  _METHODSERVICE._options = None
  _METHODSERVICE._serialized_options = b'\302\355\032\007\n\003api\020\002'
  _METHODSERVICE.methods_by_name['Get']._options = None
  _METHODSERVICE.methods_by_name['Get']._serialized_options = b'\302\355\032\014\n\nGetMethods'
  _VERSIONSERVICE._options = None
  _VERSIONSERVICE._serialized_options = b'\302\355\032\007\n\003api\020\002'
  _VERSIONSERVICE.methods_by_name['Get']._options = None
  _VERSIONSERVICE.methods_by_name['Get']._serialized_options = b'\302\355\032\014\n\nGetVersion'
  _COMPILEPROTOREQUEST._serialized_start=70
  _COMPILEPROTOREQUEST._serialized_end=91
  _COMPILEPROTORESPONSE._serialized_start=93
  _COMPILEPROTORESPONSE._serialized_end=212
  _COMPILEPROTORESPONSE_PROTOFILE._serialized_start=187
  _COMPILEPROTORESPONSE_PROTOFILE._serialized_end=212
  _METHODGETREQUEST._serialized_start=214
  _METHODGETREQUEST._serialized_end=232
  _METHODGETRESPONSE._serialized_start=234
  _METHODGETRESPONSE._serialized_end=336
  _METHODGETRESPONSE_METHOD._serialized_start=312
  _METHODGETRESPONSE_METHOD._serialized_end=336
  _VERSIONGETREQUEST._serialized_start=338
  _VERSIONGETREQUEST._serialized_end=357
  _VERSIONGETRESPONSE._serialized_start=360
  _VERSIONGETRESPONSE._serialized_end=493
  _VERSIONGETRESPONSE_VERSION._serialized_start=441
  _VERSIONGETRESPONSE_VERSION._serialized_end=493
  _APISERVICE._serialized_start=495
  _APISERVICE._serialized_end=607
  _METHODSERVICE._serialized_start=609
  _METHODSERVICE._serialized_end=727
  _VERSIONSERVICE._serialized_start=729
  _VERSIONSERVICE._serialized_end=850
# @@protoc_insertion_point(module_scope)
