# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/observability.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromite.api import image_pb2 as chromite_dot_api_dot_image__pb2
from chromite.api.gen_sdk.chromite.observability import sizes_pb2 as chromite_dot_observability_dot_sizes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromite/api/observability.proto',
  package='chromite.api',
  syntax='proto3',
  serialized_options=b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api',
  serialized_pb=b'\n chromite/api/observability.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x18\x63hromite/api/image.proto\x1a\"chromite/observability/sizes.proto\"D\n\x17GetImageSizeDataRequest\x12)\n\x0c\x62uilt_images\x18\x01 \x03(\x0b\x32\x13.chromite.api.Image\"Q\n\x18GetImageSizeDataResponse\x12\x35\n\nimage_data\x18\x01 \x03(\x0b\x32!.chromite.observability.ImageData2\x90\x01\n\x14ObservabilityService\x12\x61\n\x10GetImageSizeData\x12%.chromite.api.GetImageSizeDataRequest\x1a&.chromite.api.GetImageSizeDataResponse\x1a\x15\xc2\xed\x1a\x11\n\robservability\x10\x01\x42\x38Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3'
  ,
  dependencies=[chromite_dot_api_dot_build__api__pb2.DESCRIPTOR,chromite_dot_api_dot_image__pb2.DESCRIPTOR,chromite_dot_observability_dot_sizes__pb2.DESCRIPTOR,])




_GETIMAGESIZEDATAREQUEST = _descriptor.Descriptor(
  name='GetImageSizeDataRequest',
  full_name='chromite.api.GetImageSizeDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='built_images', full_name='chromite.api.GetImageSizeDataRequest.built_images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=210,
)


_GETIMAGESIZEDATARESPONSE = _descriptor.Descriptor(
  name='GetImageSizeDataResponse',
  full_name='chromite.api.GetImageSizeDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='chromite.api.GetImageSizeDataResponse.image_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=293,
)

_GETIMAGESIZEDATAREQUEST.fields_by_name['built_images'].message_type = chromite_dot_api_dot_image__pb2._IMAGE
_GETIMAGESIZEDATARESPONSE.fields_by_name['image_data'].message_type = chromite_dot_observability_dot_sizes__pb2._IMAGEDATA
DESCRIPTOR.message_types_by_name['GetImageSizeDataRequest'] = _GETIMAGESIZEDATAREQUEST
DESCRIPTOR.message_types_by_name['GetImageSizeDataResponse'] = _GETIMAGESIZEDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetImageSizeDataRequest = _reflection.GeneratedProtocolMessageType('GetImageSizeDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGESIZEDATAREQUEST,
  '__module__' : 'chromite.api.observability_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.GetImageSizeDataRequest)
  })
_sym_db.RegisterMessage(GetImageSizeDataRequest)

GetImageSizeDataResponse = _reflection.GeneratedProtocolMessageType('GetImageSizeDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGESIZEDATARESPONSE,
  '__module__' : 'chromite.api.observability_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.GetImageSizeDataResponse)
  })
_sym_db.RegisterMessage(GetImageSizeDataResponse)


DESCRIPTOR._options = None

_OBSERVABILITYSERVICE = _descriptor.ServiceDescriptor(
  name='ObservabilityService',
  full_name='chromite.api.ObservabilityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=b'\302\355\032\021\n\robservability\020\001',
  serialized_start=296,
  serialized_end=440,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetImageSizeData',
    full_name='chromite.api.ObservabilityService.GetImageSizeData',
    index=0,
    containing_service=None,
    input_type=_GETIMAGESIZEDATAREQUEST,
    output_type=_GETIMAGESIZEDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBSERVABILITYSERVICE)

DESCRIPTOR.services_by_name['ObservabilityService'] = _OBSERVABILITYSERVICE

# @@protoc_insertion_point(module_scope)
