# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/remote_test_driver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%chromite/api/remote_test_driver.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x17\x63hromiumos/common.proto\"a\n\x0f\x41ssembleRequest\x12\"\n\x06\x63hroot\x18\x01 \x01(\x0b\x32\x12.chromiumos.Chroot\x12*\n\ntarget_dir\x18\x02 \x01(\x0b\x32\x16.chromiumos.ResultPath\"O\n\x10\x41ssembleResponse\x12;\n\x13remote_test_drivers\x18\x01 \x03(\x0b\x32\x1e.chromite.api.RemoteTestDriver\";\n\x10RemoteTestDriver\x12\'\n\rbuild_context\x18\x01 \x01(\x0b\x32\x10.chromiumos.Path2\x80\x01\n\x17RemoteTestDriverService\x12I\n\x08\x41ssemble\x12\x1d.chromite.api.AssembleRequest\x1a\x1e.chromite.api.AssembleResponse\x1a\x1a\xc2\xed\x1a\x16\n\x12remote_test_driver\x10\x01\x42\x38Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3')



_ASSEMBLEREQUEST = DESCRIPTOR.message_types_by_name['AssembleRequest']
_ASSEMBLERESPONSE = DESCRIPTOR.message_types_by_name['AssembleResponse']
_REMOTETESTDRIVER = DESCRIPTOR.message_types_by_name['RemoteTestDriver']
AssembleRequest = _reflection.GeneratedProtocolMessageType('AssembleRequest', (_message.Message,), {
  'DESCRIPTOR' : _ASSEMBLEREQUEST,
  '__module__' : 'chromite.api.remote_test_driver_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.AssembleRequest)
  })
_sym_db.RegisterMessage(AssembleRequest)

AssembleResponse = _reflection.GeneratedProtocolMessageType('AssembleResponse', (_message.Message,), {
  'DESCRIPTOR' : _ASSEMBLERESPONSE,
  '__module__' : 'chromite.api.remote_test_driver_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.AssembleResponse)
  })
_sym_db.RegisterMessage(AssembleResponse)

RemoteTestDriver = _reflection.GeneratedProtocolMessageType('RemoteTestDriver', (_message.Message,), {
  'DESCRIPTOR' : _REMOTETESTDRIVER,
  '__module__' : 'chromite.api.remote_test_driver_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.RemoteTestDriver)
  })
_sym_db.RegisterMessage(RemoteTestDriver)

_REMOTETESTDRIVERSERVICE = DESCRIPTOR.services_by_name['RemoteTestDriverService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api'
  _REMOTETESTDRIVERSERVICE._options = None
  _REMOTETESTDRIVERSERVICE._serialized_options = b'\302\355\032\026\n\022remote_test_driver\020\001'
  _ASSEMBLEREQUEST._serialized_start=110
  _ASSEMBLEREQUEST._serialized_end=207
  _ASSEMBLERESPONSE._serialized_start=209
  _ASSEMBLERESPONSE._serialized_end=288
  _REMOTETESTDRIVER._serialized_start=290
  _REMOTETESTDRIVER._serialized_end=349
  _REMOTETESTDRIVERSERVICE._serialized_start=352
  _REMOTETESTDRIVERSERVICE._serialized_end=480
# @@protoc_insertion_point(module_scope)
