# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_test_cli.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api import test_case_result_pb2 as chromiumos_dot_test_dot_api_dot_test__case__result__pb2
from chromite.api.gen_sdk.chromiumos.test.api import test_suite_pb2 as chromiumos_dot_test_dot_api_dot_test__suite__pb2
from chromite.api.gen_sdk.chromiumos.test.lab.api import dut_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_dut__pb2
from chromite.api.gen_sdk.chromiumos.test.lab.api import ip_endpoint_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/api/cros_test_cli.proto',
  package='chromiumos.test.api',
  syntax='proto3',
  serialized_options=b'Z-go.chromium.org/chromiumos/config/go/test/api',
  serialized_pb=b'\n\'chromiumos/test/api/cros_test_cli.proto\x12\x13\x63hromiumos.test.api\x1a*chromiumos/test/api/test_case_result.proto\x1a$chromiumos/test/api/test_suite.proto\x1a!chromiumos/test/lab/api/dut.proto\x1a)chromiumos/test/lab/api/ip_endpoint.proto\"\xb2\x03\n\x0f\x43rosTestRequest\x12\x33\n\x0btest_suites\x18\x01 \x03(\x0b\x32\x1e.chromiumos.test.api.TestSuite\x12<\n\x07primary\x18\x02 \x01(\x0b\x32+.chromiumos.test.api.CrosTestRequest.Device\x12?\n\ncompanions\x18\x03 \x03(\x0b\x32+.chromiumos.test.api.CrosTestRequest.Device\x12=\n\x10inventory_server\x18\x04 \x01(\x0b\x32#.chromiumos.test.lab.api.IpEndpoint\x1a\xab\x01\n\x06\x44\x65vice\x12)\n\x03\x64ut\x18\x01 \x01(\x0b\x32\x1c.chromiumos.test.lab.api.Dut\x12\x37\n\ndut_server\x18\x02 \x01(\x0b\x32#.chromiumos.test.lab.api.IpEndpoint\x12=\n\x10provision_server\x18\x03 \x01(\x0b\x32#.chromiumos.test.lab.api.IpEndpoint\"R\n\x10\x43rosTestResponse\x12>\n\x11test_case_results\x18\x01 \x03(\x0b\x32#.chromiumos.test.api.TestCaseResultB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3'
  ,
  dependencies=[chromiumos_dot_test_dot_api_dot_test__case__result__pb2.DESCRIPTOR,chromiumos_dot_test_dot_api_dot_test__suite__pb2.DESCRIPTOR,chromiumos_dot_test_dot_lab_dot_api_dot_dut__pb2.DESCRIPTOR,chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2.DESCRIPTOR,])




_CROSTESTREQUEST_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='chromiumos.test.api.CrosTestRequest.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dut', full_name='chromiumos.test.api.CrosTestRequest.Device.dut', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dut_server', full_name='chromiumos.test.api.CrosTestRequest.Device.dut_server', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provision_server', full_name='chromiumos.test.api.CrosTestRequest.Device.provision_server', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=659,
)

_CROSTESTREQUEST = _descriptor.Descriptor(
  name='CrosTestRequest',
  full_name='chromiumos.test.api.CrosTestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_suites', full_name='chromiumos.test.api.CrosTestRequest.test_suites', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='primary', full_name='chromiumos.test.api.CrosTestRequest.primary', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='companions', full_name='chromiumos.test.api.CrosTestRequest.companions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inventory_server', full_name='chromiumos.test.api.CrosTestRequest.inventory_server', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CROSTESTREQUEST_DEVICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=659,
)


_CROSTESTRESPONSE = _descriptor.Descriptor(
  name='CrosTestResponse',
  full_name='chromiumos.test.api.CrosTestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_case_results', full_name='chromiumos.test.api.CrosTestResponse.test_case_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=743,
)

_CROSTESTREQUEST_DEVICE.fields_by_name['dut'].message_type = chromiumos_dot_test_dot_lab_dot_api_dot_dut__pb2._DUT
_CROSTESTREQUEST_DEVICE.fields_by_name['dut_server'].message_type = chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2._IPENDPOINT
_CROSTESTREQUEST_DEVICE.fields_by_name['provision_server'].message_type = chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2._IPENDPOINT
_CROSTESTREQUEST_DEVICE.containing_type = _CROSTESTREQUEST
_CROSTESTREQUEST.fields_by_name['test_suites'].message_type = chromiumos_dot_test_dot_api_dot_test__suite__pb2._TESTSUITE
_CROSTESTREQUEST.fields_by_name['primary'].message_type = _CROSTESTREQUEST_DEVICE
_CROSTESTREQUEST.fields_by_name['companions'].message_type = _CROSTESTREQUEST_DEVICE
_CROSTESTREQUEST.fields_by_name['inventory_server'].message_type = chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2._IPENDPOINT
_CROSTESTRESPONSE.fields_by_name['test_case_results'].message_type = chromiumos_dot_test_dot_api_dot_test__case__result__pb2._TESTCASERESULT
DESCRIPTOR.message_types_by_name['CrosTestRequest'] = _CROSTESTREQUEST
DESCRIPTOR.message_types_by_name['CrosTestResponse'] = _CROSTESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrosTestRequest = _reflection.GeneratedProtocolMessageType('CrosTestRequest', (_message.Message,), {

  'Device' : _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
    'DESCRIPTOR' : _CROSTESTREQUEST_DEVICE,
    '__module__' : 'chromiumos.test.api.cros_test_cli_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.CrosTestRequest.Device)
    })
  ,
  'DESCRIPTOR' : _CROSTESTREQUEST,
  '__module__' : 'chromiumos.test.api.cros_test_cli_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.CrosTestRequest)
  })
_sym_db.RegisterMessage(CrosTestRequest)
_sym_db.RegisterMessage(CrosTestRequest.Device)

CrosTestResponse = _reflection.GeneratedProtocolMessageType('CrosTestResponse', (_message.Message,), {
  'DESCRIPTOR' : _CROSTESTRESPONSE,
  '__module__' : 'chromiumos.test.api.cros_test_cli_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.CrosTestResponse)
  })
_sym_db.RegisterMessage(CrosTestResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
