# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_tool_runner_container_service_extensions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGchromiumos/test/api/cros_tool_runner_container_service_extensions.proto\x12\x13\x63hromiumos.test.api\"C\n\x17LoginRegistryExtensions\x12(\n gcloud_auth_service_account_args\x18\x01 \x03(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_LOGINREGISTRYEXTENSIONS = DESCRIPTOR.message_types_by_name['LoginRegistryExtensions']
LoginRegistryExtensions = _reflection.GeneratedProtocolMessageType('LoginRegistryExtensions', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREGISTRYEXTENSIONS,
  '__module__' : 'chromiumos.test.api.cros_tool_runner_container_service_extensions_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.LoginRegistryExtensions)
  })
_sym_db.RegisterMessage(LoginRegistryExtensions)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _LOGINREGISTRYEXTENSIONS._serialized_start=96
  _LOGINREGISTRYEXTENSIONS._serialized_end=163
# @@protoc_insertion_point(module_scope)
