# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_publish_cli.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*chromiumos/test/api/cros_publish_cli.proto\x12\x13\x63hromiumos.test.api\"C\n\x12\x43rosPublishRequest\x12\x14\n\x0cgs_directory\x18\x01 \x01(\t\x12\x17\n\x0flocal_directory\x18\x02 \x01(\t\"K\n\x13\x43rosPublishResponse\x12\x0e\n\x06gs_url\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_CROSPUBLISHREQUEST = DESCRIPTOR.message_types_by_name['CrosPublishRequest']
_CROSPUBLISHRESPONSE = DESCRIPTOR.message_types_by_name['CrosPublishResponse']
CrosPublishRequest = _reflection.GeneratedProtocolMessageType('CrosPublishRequest', (_message.Message,), {
  'DESCRIPTOR' : _CROSPUBLISHREQUEST,
  '__module__' : 'chromiumos.test.api.cros_publish_cli_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.CrosPublishRequest)
  })
_sym_db.RegisterMessage(CrosPublishRequest)

CrosPublishResponse = _reflection.GeneratedProtocolMessageType('CrosPublishResponse', (_message.Message,), {
  'DESCRIPTOR' : _CROSPUBLISHRESPONSE,
  '__module__' : 'chromiumos.test.api.cros_publish_cli_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.CrosPublishResponse)
  })
_sym_db.RegisterMessage(CrosPublishResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _CROSPUBLISHREQUEST._serialized_start=67
  _CROSPUBLISHREQUEST._serialized_end=134
  _CROSPUBLISHRESPONSE._serialized_start=136
  _CROSPUBLISHRESPONSE._serialized_end=211
# @@protoc_insertion_point(module_scope)
