# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_tool_runner_container_service_extensions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/api/cros_tool_runner_container_service_extensions.proto',
  package='chromiumos.test.api',
  syntax='proto3',
  serialized_options=b'Z-go.chromium.org/chromiumos/config/go/test/api',
  serialized_pb=b'\nGchromiumos/test/api/cros_tool_runner_container_service_extensions.proto\x12\x13\x63hromiumos.test.api\"C\n\x17LoginRegistryExtensions\x12(\n gcloud_auth_service_account_args\x18\x01 \x03(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3'
)




_LOGINREGISTRYEXTENSIONS = _descriptor.Descriptor(
  name='LoginRegistryExtensions',
  full_name='chromiumos.test.api.LoginRegistryExtensions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gcloud_auth_service_account_args', full_name='chromiumos.test.api.LoginRegistryExtensions.gcloud_auth_service_account_args', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['LoginRegistryExtensions'] = _LOGINREGISTRYEXTENSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginRegistryExtensions = _reflection.GeneratedProtocolMessageType('LoginRegistryExtensions', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREGISTRYEXTENSIONS,
  '__module__' : 'chromiumos.test.api.cros_tool_runner_container_service_extensions_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.LoginRegistryExtensions)
  })
_sym_db.RegisterMessage(LoginRegistryExtensions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
