# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/lacros_provision_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3chromiumos/test/api/lacros_provision_metadata.proto\x12\x13\x63hromiumos.test.api\"R\n\x17LaCrOSProvisionMetadata\x12\x18\n\x10override_version\x18\x01 \x01(\t\x12\x1d\n\x15override_install_path\x18\x02 \x01(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_LACROSPROVISIONMETADATA = DESCRIPTOR.message_types_by_name['LaCrOSProvisionMetadata']
LaCrOSProvisionMetadata = _reflection.GeneratedProtocolMessageType('LaCrOSProvisionMetadata', (_message.Message,), {
  'DESCRIPTOR' : _LACROSPROVISIONMETADATA,
  '__module__' : 'chromiumos.test.api.lacros_provision_metadata_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.LaCrOSProvisionMetadata)
  })
_sym_db.RegisterMessage(LaCrOSProvisionMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _LACROSPROVISIONMETADATA._serialized_start=76
  _LACROSPROVISIONMETADATA._serialized_end=158
# @@protoc_insertion_point(module_scope)
