# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/plan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api import coverage_rule_pb2 as chromiumos_dot_test_dot_api_dot_coverage__rule__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63hromiumos/test/api/plan.proto\x12\x13\x63hromiumos.test.api\x1a\'chromiumos/test/api/coverage_rule.proto\"\xa0\x01\n\nHWTestPlan\x12\x36\n\x02id\x18\x01 \x01(\x0b\x32*.chromiumos.test.api.HWTestPlan.TestPlanId\x12\x39\n\x0e\x63overage_rules\x18\x02 \x03(\x0b\x32!.chromiumos.test.api.CoverageRule\x1a\x1b\n\nTestPlanId\x12\r\n\x05value\x18\x01 \x01(\t:\x02\x18\x01\x42/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_HWTESTPLAN = DESCRIPTOR.message_types_by_name['HWTestPlan']
_HWTESTPLAN_TESTPLANID = _HWTESTPLAN.nested_types_by_name['TestPlanId']
HWTestPlan = _reflection.GeneratedProtocolMessageType('HWTestPlan', (_message.Message,), {

  'TestPlanId' : _reflection.GeneratedProtocolMessageType('TestPlanId', (_message.Message,), {
    'DESCRIPTOR' : _HWTESTPLAN_TESTPLANID,
    '__module__' : 'chromiumos.test.api.plan_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.HWTestPlan.TestPlanId)
    })
  ,
  'DESCRIPTOR' : _HWTESTPLAN,
  '__module__' : 'chromiumos.test.api.plan_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.HWTestPlan)
  })
_sym_db.RegisterMessage(HWTestPlan)
_sym_db.RegisterMessage(HWTestPlan.TestPlanId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _HWTESTPLAN._options = None
  _HWTESTPLAN._serialized_options = b'\030\001'
  _HWTESTPLAN._serialized_start=97
  _HWTESTPLAN._serialized_end=257
  _HWTESTPLAN_TESTPLANID._serialized_start=226
  _HWTESTPLAN_TESTPLANID._serialized_end=253
# @@protoc_insertion_point(module_scope)
