# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/publish_gcs_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos import storage_path_pb2 as chromiumos_dot_storage__path__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.chromiumos/test/api/publish_gcs_metadata.proto\x12\x13\x63hromiumos.test.api\x1a\x1d\x63hromiumos/storage_path.proto\"\x81\x01\n\x12PublishGcsMetadata\x12)\n\x08gcs_path\x18\x01 \x01(\x0b\x32\x17.chromiumos.StoragePath\x12@\n\x1fservice_account_creds_file_path\x18\x02 \x01(\x0b\x32\x17.chromiumos.StoragePathB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_PUBLISHGCSMETADATA = DESCRIPTOR.message_types_by_name['PublishGcsMetadata']
PublishGcsMetadata = _reflection.GeneratedProtocolMessageType('PublishGcsMetadata', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHGCSMETADATA,
  '__module__' : 'chromiumos.test.api.publish_gcs_metadata_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.PublishGcsMetadata)
  })
_sym_db.RegisterMessage(PublishGcsMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _PUBLISHGCSMETADATA._serialized_start=103
  _PUBLISHGCSMETADATA._serialized_end=232
# @@protoc_insertion_point(module_scope)
