# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/test_case.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#chromiumos/test/api/test_case.proto\x12\x13\x63hromiumos.test.api\"\xff\x01\n\x08TestCase\x12,\n\x02id\x18\x01 \x01(\x0b\x32 .chromiumos.test.api.TestCase.Id\x12\x0c\n\x04name\x18\x02 \x01(\t\x12/\n\x04tags\x18\x03 \x03(\x0b\x32!.chromiumos.test.api.TestCase.Tag\x12>\n\x0c\x64\x65pendencies\x18\x04 \x03(\x0b\x32(.chromiumos.test.api.TestCase.Dependency\x1a\x13\n\x02Id\x12\r\n\x05value\x18\x01 \x01(\t\x1a\x14\n\x03Tag\x12\r\n\x05value\x18\x01 \x01(\t\x1a\x1b\n\nDependency\x12\r\n\x05value\x18\x01 \x01(\t\"I\n\x0eTestCaseIdList\x12\x37\n\rtest_case_ids\x18\x01 \x03(\x0b\x32 .chromiumos.test.api.TestCase.Id\"A\n\x0cTestCaseList\x12\x31\n\ntest_cases\x18\x01 \x03(\x0b\x32\x1d.chromiumos.test.api.TestCaseB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_TESTCASE = DESCRIPTOR.message_types_by_name['TestCase']
_TESTCASE_ID = _TESTCASE.nested_types_by_name['Id']
_TESTCASE_TAG = _TESTCASE.nested_types_by_name['Tag']
_TESTCASE_DEPENDENCY = _TESTCASE.nested_types_by_name['Dependency']
_TESTCASEIDLIST = DESCRIPTOR.message_types_by_name['TestCaseIdList']
_TESTCASELIST = DESCRIPTOR.message_types_by_name['TestCaseList']
TestCase = _reflection.GeneratedProtocolMessageType('TestCase', (_message.Message,), {

  'Id' : _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
    'DESCRIPTOR' : _TESTCASE_ID,
    '__module__' : 'chromiumos.test.api.test_case_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.TestCase.Id)
    })
  ,

  'Tag' : _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), {
    'DESCRIPTOR' : _TESTCASE_TAG,
    '__module__' : 'chromiumos.test.api.test_case_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.TestCase.Tag)
    })
  ,

  'Dependency' : _reflection.GeneratedProtocolMessageType('Dependency', (_message.Message,), {
    'DESCRIPTOR' : _TESTCASE_DEPENDENCY,
    '__module__' : 'chromiumos.test.api.test_case_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.TestCase.Dependency)
    })
  ,
  'DESCRIPTOR' : _TESTCASE,
  '__module__' : 'chromiumos.test.api.test_case_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.TestCase)
  })
_sym_db.RegisterMessage(TestCase)
_sym_db.RegisterMessage(TestCase.Id)
_sym_db.RegisterMessage(TestCase.Tag)
_sym_db.RegisterMessage(TestCase.Dependency)

TestCaseIdList = _reflection.GeneratedProtocolMessageType('TestCaseIdList', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASEIDLIST,
  '__module__' : 'chromiumos.test.api.test_case_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.TestCaseIdList)
  })
_sym_db.RegisterMessage(TestCaseIdList)

TestCaseList = _reflection.GeneratedProtocolMessageType('TestCaseList', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASELIST,
  '__module__' : 'chromiumos.test.api.test_case_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.TestCaseList)
  })
_sym_db.RegisterMessage(TestCaseList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _TESTCASE._serialized_start=61
  _TESTCASE._serialized_end=316
  _TESTCASE_ID._serialized_start=246
  _TESTCASE_ID._serialized_end=265
  _TESTCASE_TAG._serialized_start=267
  _TESTCASE_TAG._serialized_end=287
  _TESTCASE_DEPENDENCY._serialized_start=289
  _TESTCASE_DEPENDENCY._serialized_end=316
  _TESTCASEIDLIST._serialized_start=318
  _TESTCASEIDLIST._serialized_end=391
  _TESTCASELIST._serialized_start=393
  _TESTCASELIST._serialized_end=458
# @@protoc_insertion_point(module_scope)
