# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/test_execution_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1chromiumos/test/api/test_execution_metadata.proto\x12\x13\x63hromiumos.test.api\"\x81\x01\n\x19\x41utotestExecutionMetadata\x12@\n\x04\x61rgs\x18\x01 \x03(\x0b\x32\x32.chromiumos.test.api.AutotestExecutionMetadata.Arg\x1a\"\n\x03\x41rg\x12\x0c\n\x04\x66lag\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_AUTOTESTEXECUTIONMETADATA = DESCRIPTOR.message_types_by_name['AutotestExecutionMetadata']
_AUTOTESTEXECUTIONMETADATA_ARG = _AUTOTESTEXECUTIONMETADATA.nested_types_by_name['Arg']
AutotestExecutionMetadata = _reflection.GeneratedProtocolMessageType('AutotestExecutionMetadata', (_message.Message,), {

  'Arg' : _reflection.GeneratedProtocolMessageType('Arg', (_message.Message,), {
    'DESCRIPTOR' : _AUTOTESTEXECUTIONMETADATA_ARG,
    '__module__' : 'chromiumos.test.api.test_execution_metadata_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.AutotestExecutionMetadata.Arg)
    })
  ,
  'DESCRIPTOR' : _AUTOTESTEXECUTIONMETADATA,
  '__module__' : 'chromiumos.test.api.test_execution_metadata_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.AutotestExecutionMetadata)
  })
_sym_db.RegisterMessage(AutotestExecutionMetadata)
_sym_db.RegisterMessage(AutotestExecutionMetadata.Arg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _AUTOTESTEXECUTIONMETADATA._serialized_start=75
  _AUTOTESTEXECUTIONMETADATA._serialized_end=204
  _AUTOTESTEXECUTIONMETADATA_ARG._serialized_start=170
  _AUTOTESTEXECUTIONMETADATA_ARG._serialized_end=204
# @@protoc_insertion_point(module_scope)
