# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/v2/request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2
from chromite.api.gen_sdk.chromiumos.test.api.v1 import plan_pb2 as chromiumos_dot_test_dot_api_dot_v1_dot_plan__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etest_platform/v2/request.proto\x12\x10test_platform.v2\x1a\x17\x63hromiumos/common.proto\x1a!chromiumos/test/api/v1/plan.proto\"\x7f\n\x08TestSpec\x12,\n\x0f\x62uild_directory\x18\x01 \x01(\x0b\x32\x13.chromiumos.GcsPath\x12=\n\x0fhw_test_plan_v1\x18\x02 \x01(\x0b\x32\".chromiumos.test.api.v1.HWTestPlanH\x00\x42\x06\n\x04spec\"\xe7\x01\n\x07Request\x12,\n\x0f\x62uild_directory\x18\x01 \x01(\x0b\x32\x13.chromiumos.GcsPath\x12.\n\ntest_specs\x18\x02 \x03(\x0b\x32\x1a.test_platform.v2.TestSpec\x12G\n\x12scheduler_settings\x18\x03 \x01(\x0b\x32+.test_platform.v2.Request.SchedulerSettings\x1a\x35\n\x11SchedulerSettings\x12\x0c\n\x04pool\x18\x01 \x01(\t\x12\x12\n\nqs_account\x18\x02 \x01(\tBJZHgo.chromium.org/chromiumos/infra/proto/go/test_platform/v2;test_platformb\x06proto3')



_TESTSPEC = DESCRIPTOR.message_types_by_name['TestSpec']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REQUEST_SCHEDULERSETTINGS = _REQUEST.nested_types_by_name['SchedulerSettings']
TestSpec = _reflection.GeneratedProtocolMessageType('TestSpec', (_message.Message,), {
  'DESCRIPTOR' : _TESTSPEC,
  '__module__' : 'test_platform.v2.request_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.v2.TestSpec)
  })
_sym_db.RegisterMessage(TestSpec)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'SchedulerSettings' : _reflection.GeneratedProtocolMessageType('SchedulerSettings', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_SCHEDULERSETTINGS,
    '__module__' : 'test_platform.v2.request_pb2'
    # @@protoc_insertion_point(class_scope:test_platform.v2.Request.SchedulerSettings)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'test_platform.v2.request_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.v2.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.SchedulerSettings)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgo.chromium.org/chromiumos/infra/proto/go/test_platform/v2;test_platform'
  _TESTSPEC._serialized_start=112
  _TESTSPEC._serialized_end=239
  _REQUEST._serialized_start=242
  _REQUEST._serialized_end=473
  _REQUEST_SCHEDULERSETTINGS._serialized_start=420
  _REQUEST_SCHEDULERSETTINGS._serialized_end=473
# @@protoc_insertion_point(module_scope)
