# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/prototype/release_target_id.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3chromiumos/config/prototype/release_target_id.proto\x12\x1b\x63hromiumos.config.prototype\" \n\x0fReleaseTargetId\x12\r\n\x05value\x18\x01 \x01(\tB0Z.go.chromium.org/chromiumos/config/go/prototypeb\x06proto3')



_RELEASETARGETID = DESCRIPTOR.message_types_by_name['ReleaseTargetId']
ReleaseTargetId = _reflection.GeneratedProtocolMessageType('ReleaseTargetId', (_message.Message,), {
  'DESCRIPTOR' : _RELEASETARGETID,
  '__module__' : 'chromiumos.config.prototype.release_target_id_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.prototype.ReleaseTargetId)
  })
_sym_db.RegisterMessage(ReleaseTargetId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.go.chromium.org/chromiumos/config/go/prototype'
  _RELEASETARGETID._serialized_start=84
  _RELEASETARGETID._serialized_end=116
# @@protoc_insertion_point(module_scope)
