# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/common/task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftest_platform/common/task.proto\x12\x14test_platform.common\"4\n\x0bTaskLogData\x12\x0e\n\x06gs_url\x18\x01 \x01(\t\x12\x15\n\rstainless_url\x18\x02 \x01(\tB@Z>go.chromium.org/chromiumos/infra/proto/go/test_platform/commonb\x06proto3')



_TASKLOGDATA = DESCRIPTOR.message_types_by_name['TaskLogData']
TaskLogData = _reflection.GeneratedProtocolMessageType('TaskLogData', (_message.Message,), {
  'DESCRIPTOR' : _TASKLOGDATA,
  '__module__' : 'test_platform.common.task_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.common.TaskLogData)
  })
_sym_db.RegisterMessage(TaskLogData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z>go.chromium.org/chromiumos/infra/proto/go/test_platform/common'
  _TASKLOGDATA._serialized_start=57
  _TASKLOGDATA._serialized_end=109
# @@protoc_insertion_point(module_scope)
