# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/dut_tracking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos import bot_scaling_pb2 as chromiumos_dot_bot__scaling__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63hromiumos/dut_tracking.proto\x12\nchromiumos\x1a\x1c\x63hromiumos/bot_scaling.proto\"\xe7\x01\n\x0eTrackingPolicy\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\ndimensions\x18\x02 \x03(\x0b\x32\x1d.chromiumos.SwarmingDimension\x12)\n\x05modes\x18\x03 \x03(\x0e\x32\x1a.chromiumos.MonitoringMode\x12\x16\n\x0elookback_hours\x18\x04 \x01(\x11\x12\x36\n\x0ftask_dimensions\x18\x05 \x03(\x0b\x32\x1d.chromiumos.SwarmingDimension\x12\x19\n\x11swarming_instance\x18\x06 \x01(\t\"A\n\x11TrackingPolicyCfg\x12,\n\x08policies\x18\x01 \x03(\x0b\x32\x1a.chromiumos.TrackingPolicy*b\n\x0eMonitoringMode\x12\x14\n\x10\x44\x45\x46\x41ULT_TRACKING\x10\x00\x12\x12\n\x0eTASK_BOT_COUNT\x10\x01\x12\x11\n\rMAX_PEND_TIME\x10\x02\x12\x13\n\x0fPASS_FAIL_COUNT\x10\x03\x42Y\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumosb\x06proto3')

_MONITORINGMODE = DESCRIPTOR.enum_types_by_name['MonitoringMode']
MonitoringMode = enum_type_wrapper.EnumTypeWrapper(_MONITORINGMODE)
DEFAULT_TRACKING = 0
TASK_BOT_COUNT = 1
MAX_PEND_TIME = 2
PASS_FAIL_COUNT = 3


_TRACKINGPOLICY = DESCRIPTOR.message_types_by_name['TrackingPolicy']
_TRACKINGPOLICYCFG = DESCRIPTOR.message_types_by_name['TrackingPolicyCfg']
TrackingPolicy = _reflection.GeneratedProtocolMessageType('TrackingPolicy', (_message.Message,), {
  'DESCRIPTOR' : _TRACKINGPOLICY,
  '__module__' : 'chromiumos.dut_tracking_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.TrackingPolicy)
  })
_sym_db.RegisterMessage(TrackingPolicy)

TrackingPolicyCfg = _reflection.GeneratedProtocolMessageType('TrackingPolicyCfg', (_message.Message,), {
  'DESCRIPTOR' : _TRACKINGPOLICYCFG,
  '__module__' : 'chromiumos.dut_tracking_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.TrackingPolicyCfg)
  })
_sym_db.RegisterMessage(TrackingPolicyCfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumos'
  _MONITORINGMODE._serialized_start=376
  _MONITORINGMODE._serialized_end=474
  _TRACKINGPOLICY._serialized_start=76
  _TRACKINGPOLICY._serialized_end=307
  _TRACKINGPOLICYCFG._serialized_start=309
  _TRACKINGPOLICYCFG._serialized_end=374
# @@protoc_insertion_point(module_scope)
