# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/greenness.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/greenness.proto',
  package='chromiumos',
  syntax='proto3',
  serialized_options=b'\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumos',
  serialized_pb=b'\n\x1a\x63hromiumos/greenness.proto\x12\nchromiumos\"\x9f\x01\n\x12\x41ggregateGreenness\x12\x18\n\x10\x61ggregate_metric\x18\x01 \x01(\x03\x12\x42\n\x10target_greenness\x18\x02 \x03(\x0b\x32(.chromiumos.AggregateGreenness.Greenness\x1a+\n\tGreenness\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\x03\x42Y\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumosb\x06proto3'
)




_AGGREGATEGREENNESS_GREENNESS = _descriptor.Descriptor(
  name='Greenness',
  full_name='chromiumos.AggregateGreenness.Greenness',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='chromiumos.AggregateGreenness.Greenness.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric', full_name='chromiumos.AggregateGreenness.Greenness.metric', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=202,
)

_AGGREGATEGREENNESS = _descriptor.Descriptor(
  name='AggregateGreenness',
  full_name='chromiumos.AggregateGreenness',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aggregate_metric', full_name='chromiumos.AggregateGreenness.aggregate_metric', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_greenness', full_name='chromiumos.AggregateGreenness.target_greenness', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGGREGATEGREENNESS_GREENNESS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=202,
)

_AGGREGATEGREENNESS_GREENNESS.containing_type = _AGGREGATEGREENNESS
_AGGREGATEGREENNESS.fields_by_name['target_greenness'].message_type = _AGGREGATEGREENNESS_GREENNESS
DESCRIPTOR.message_types_by_name['AggregateGreenness'] = _AGGREGATEGREENNESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AggregateGreenness = _reflection.GeneratedProtocolMessageType('AggregateGreenness', (_message.Message,), {

  'Greenness' : _reflection.GeneratedProtocolMessageType('Greenness', (_message.Message,), {
    'DESCRIPTOR' : _AGGREGATEGREENNESS_GREENNESS,
    '__module__' : 'chromiumos.greenness_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.AggregateGreenness.Greenness)
    })
  ,
  'DESCRIPTOR' : _AGGREGATEGREENNESS,
  '__module__' : 'chromiumos.greenness_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.AggregateGreenness)
  })
_sym_db.RegisterMessage(AggregateGreenness)
_sym_db.RegisterMessage(AggregateGreenness.Greenness)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
