# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/component_package.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.config.api import component_pb2 as chromiumos_dot_config_dot_api_dot_component__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-chromiumos/config/api/component_package.proto\x12\x15\x63hromiumos.config.api\x1a%chromiumos/config/api/component.proto\"\xd8\x08\n\x10\x43omponentPackage\x12\x31\n\x03soc\x18\x01 \x01(\x0b\x32$.chromiumos.config.api.Component.Soc\x12\x37\n\x06memory\x18\x02 \x03(\x0b\x32\'.chromiumos.config.api.Component.Memory\x12=\n\tbluetooth\x18\x03 \x01(\x0b\x32*.chromiumos.config.api.Component.Bluetooth\x12\x37\n\x06\x63\x61mera\x18\x04 \x01(\x0b\x32\'.chromiumos.config.api.Component.Camera\x12;\n\x0btouchscreen\x18\x05 \x01(\x0b\x32&.chromiumos.config.api.Component.Touch\x12\x33\n\x04wifi\x18\x06 \x01(\x0b\x32%.chromiumos.config.api.Component.Wifi\x12\x38\n\x08touchpad\x18\x07 \x01(\x0b\x32&.chromiumos.config.api.Component.Touch\x12\x44\n\rdisplay_panel\x18\x08 \x01(\x0b\x32-.chromiumos.config.api.Component.DisplayPanel\x12@\n\x0b\x61udio_codec\x18\t \x01(\x0b\x32+.chromiumos.config.api.Component.AudioCodec\x12\x39\n\x07\x62\x61ttery\x18\n \x01(\x0b\x32(.chromiumos.config.api.Component.Battery\x12\x41\n\rec_flash_chip\x18\x0b \x01(\x0b\x32*.chromiumos.config.api.Component.FlashChip\x12\x45\n\x11system_flash_chip\x18\x0c \x01(\x0b\x32*.chromiumos.config.api.Component.FlashChip\x12?\n\x02\x65\x63\x18\r \x01(\x0b\x32\x33.chromiumos.config.api.Component.EmbeddedController\x12\x39\n\x07storage\x18\x0e \x01(\x0b\x32(.chromiumos.config.api.Component.Storage\x12\x31\n\x03tpm\x18\x0f \x01(\x0b\x32$.chromiumos.config.api.Component.Tpm\x12@\n\x08usb_host\x18\x10 \x01(\x0b\x32..chromiumos.config.api.Component.Interface.Usb\x12\x37\n\x06stylus\x18\x11 \x01(\x0b\x32\'.chromiumos.config.api.Component.Stylus\x12=\n\tamplifier\x18\x12 \x01(\x0b\x32*.chromiumos.config.api.Component.AmplifierB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3')



_COMPONENTPACKAGE = DESCRIPTOR.message_types_by_name['ComponentPackage']
ComponentPackage = _reflection.GeneratedProtocolMessageType('ComponentPackage', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENTPACKAGE,
  '__module__' : 'chromiumos.config.api.component_package_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.ComponentPackage)
  })
_sym_db.RegisterMessage(ComponentPackage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/chromiumos/config/go/api'
  _COMPONENTPACKAGE._serialized_start=112
  _COMPONENTPACKAGE._serialized_end=1224
# @@protoc_insertion_point(module_scope)
