# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/design_config_id.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,chromiumos/config/api/design_config_id.proto\x12\x15\x63hromiumos.config.api\"\x9f\x01\n\x0e\x44\x65signConfigId\x12\r\n\x05value\x18\x01 \x01(\t\x1a~\n\nScanConfig\x12\x1b\n\x11smbios_name_match\x18\x01 \x01(\tH\x00\x12&\n\x1c\x64\x65vice_tree_compatible_match\x18\x02 \x01(\tH\x00\x12\x14\n\x0c\x66irmware_sku\x18\x03 \x01(\rB\x15\n\x13\x66irmware_name_matchB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3')



_DESIGNCONFIGID = DESCRIPTOR.message_types_by_name['DesignConfigId']
_DESIGNCONFIGID_SCANCONFIG = _DESIGNCONFIGID.nested_types_by_name['ScanConfig']
DesignConfigId = _reflection.GeneratedProtocolMessageType('DesignConfigId', (_message.Message,), {

  'ScanConfig' : _reflection.GeneratedProtocolMessageType('ScanConfig', (_message.Message,), {
    'DESCRIPTOR' : _DESIGNCONFIGID_SCANCONFIG,
    '__module__' : 'chromiumos.config.api.design_config_id_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.config.api.DesignConfigId.ScanConfig)
    })
  ,
  'DESCRIPTOR' : _DESIGNCONFIGID,
  '__module__' : 'chromiumos.config.api.design_config_id_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.DesignConfigId)
  })
_sym_db.RegisterMessage(DesignConfigId)
_sym_db.RegisterMessage(DesignConfigId.ScanConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/chromiumos/config/go/api'
  _DESIGNCONFIGID._serialized_start=72
  _DESIGNCONFIGID._serialized_end=231
  _DESIGNCONFIGID_SCANCONFIG._serialized_start=105
  _DESIGNCONFIGID_SCANCONFIG._serialized_end=231
# @@protoc_insertion_point(module_scope)
