# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/design_id.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%chromiumos/config/api/design_id.proto\x12\x15\x63hromiumos.config.api\"]\n\x08\x44\x65signId\x12\r\n\x05value\x18\x01 \x01(\t\x12\x42\n\x19\x63onfig_design_id_override\x18\x02 \x01(\x0b\x32\x1f.chromiumos.config.api.DesignIdB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3')



_DESIGNID = DESCRIPTOR.message_types_by_name['DesignId']
DesignId = _reflection.GeneratedProtocolMessageType('DesignId', (_message.Message,), {
  'DESCRIPTOR' : _DESIGNID,
  '__module__' : 'chromiumos.config.api.design_id_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.DesignId)
  })
_sym_db.RegisterMessage(DesignId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/chromiumos/config/go/api'
  _DESIGNID._serialized_start=64
  _DESIGNID._serialized_end=157
# @@protoc_insertion_point(module_scope)
