# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/partner_id.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&chromiumos/config/api/partner_id.proto\x12\x15\x63hromiumos.config.api\"\x1a\n\tPartnerId\x12\r\n\x05value\x18\x01 \x01(\tB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3')



_PARTNERID = DESCRIPTOR.message_types_by_name['PartnerId']
PartnerId = _reflection.GeneratedProtocolMessageType('PartnerId', (_message.Message,), {
  'DESCRIPTOR' : _PARTNERID,
  '__module__' : 'chromiumos.config.api.partner_id_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.PartnerId)
  })
_sym_db.RegisterMessage(PartnerId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/chromiumos/config/go/api'
  _PARTNERID._serialized_start=65
  _PARTNERID._serialized_end=91
# @@protoc_insertion_point(module_scope)
