# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/program_id.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/config/api/program_id.proto',
  package='chromiumos.config.api',
  syntax='proto3',
  serialized_options=b'Z(go.chromium.org/chromiumos/config/go/api',
  serialized_pb=b'\n&chromiumos/config/api/program_id.proto\x12\x15\x63hromiumos.config.api\"\x1a\n\tProgramId\x12\r\n\x05value\x18\x01 \x01(\tB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3'
)




_PROGRAMID = _descriptor.Descriptor(
  name='ProgramId',
  full_name='chromiumos.config.api.ProgramId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='chromiumos.config.api.ProgramId.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['ProgramId'] = _PROGRAMID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgramId = _reflection.GeneratedProtocolMessageType('ProgramId', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMID,
  '__module__' : 'chromiumos.config.api.program_id_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.ProgramId)
  })
_sym_db.RegisterMessage(ProgramId)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
