# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/software/bluetooth_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5chromiumos/config/api/software/bluetooth_config.proto\x12\x1e\x63hromiumos.config.api.software\"\x8a\x01\n\x0f\x42luetoothConfig\x12I\n\x05\x66lags\x18\x01 \x03(\x0b\x32:.chromiumos.config.api.software.BluetoothConfig.FlagsEntry\x1a,\n\nFlagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x42\x33Z1go.chromium.org/chromiumos/config/go/api/softwareb\x06proto3')



_BLUETOOTHCONFIG = DESCRIPTOR.message_types_by_name['BluetoothConfig']
_BLUETOOTHCONFIG_FLAGSENTRY = _BLUETOOTHCONFIG.nested_types_by_name['FlagsEntry']
BluetoothConfig = _reflection.GeneratedProtocolMessageType('BluetoothConfig', (_message.Message,), {

  'FlagsEntry' : _reflection.GeneratedProtocolMessageType('FlagsEntry', (_message.Message,), {
    'DESCRIPTOR' : _BLUETOOTHCONFIG_FLAGSENTRY,
    '__module__' : 'chromiumos.config.api.software.bluetooth_config_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.BluetoothConfig.FlagsEntry)
    })
  ,
  'DESCRIPTOR' : _BLUETOOTHCONFIG,
  '__module__' : 'chromiumos.config.api.software.bluetooth_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.BluetoothConfig)
  })
_sym_db.RegisterMessage(BluetoothConfig)
_sym_db.RegisterMessage(BluetoothConfig.FlagsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/config/go/api/software'
  _BLUETOOTHCONFIG_FLAGSENTRY._options = None
  _BLUETOOTHCONFIG_FLAGSENTRY._serialized_options = b'8\001'
  _BLUETOOTHCONFIG._serialized_start=90
  _BLUETOOTHCONFIG._serialized_end=228
  _BLUETOOTHCONFIG_FLAGSENTRY._serialized_start=184
  _BLUETOOTHCONFIG_FLAGSENTRY._serialized_end=228
# @@protoc_insertion_point(module_scope)
