# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/skylab_local_state/multihost.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.test_platform.skylab_local_state import host_info_pb2 as test__platform_dot_skylab__local__state_dot_host__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0test_platform/skylab_local_state/multihost.proto\x12 test_platform.skylab_local_state\x1a\x30test_platform/skylab_local_state/host_info.proto\"k\n\x10MultiBotHostInfo\x12\x45\n\thost_info\x18\x01 \x01(\x0b\x32\x32.test_platform.skylab_local_state.AutotestHostInfo\x12\x10\n\x08\x64ut_name\x18\x02 \x01(\tBLZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_stateb\x06proto3')



_MULTIBOTHOSTINFO = DESCRIPTOR.message_types_by_name['MultiBotHostInfo']
MultiBotHostInfo = _reflection.GeneratedProtocolMessageType('MultiBotHostInfo', (_message.Message,), {
  'DESCRIPTOR' : _MULTIBOTHOSTINFO,
  '__module__' : 'test_platform.skylab_local_state.multihost_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.skylab_local_state.MultiBotHostInfo)
  })
_sym_db.RegisterMessage(MultiBotHostInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_state'
  _MULTIBOTHOSTINFO._serialized_start=136
  _MULTIBOTHOSTINFO._serialized_end=243
# @@protoc_insertion_point(module_scope)
