# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/phosphorus/fetchcrashes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from chromite.api.gen_sdk.test_platform.phosphorus import common_pb2 as test__platform_dot_phosphorus_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+test_platform/phosphorus/fetchcrashes.proto\x12\x18test_platform.phosphorus\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%test_platform/phosphorus/common.proto\"\xbc\x01\n\x13\x46\x65tchCrashesRequest\x12\x30\n\x06\x63onfig\x18\x01 \x01(\x0b\x32 .test_platform.phosphorus.Config\x12\x14\n\x0c\x64ut_hostname\x18\x02 \x01(\t\x12,\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0eupload_crashes\x18\x04 \x01(\x08\x12\x17\n\x0buse_staging\x18\x05 \x01(\x08\x42\x02\x18\x01\"\x7f\n\x0c\x43rashSummary\x12\x11\n\texec_name\x18\x01 \x01(\t\x12\x12\n\nupload_url\x18\x02 \x01(\t\x12$\n\x1cin_progress_integration_test\x18\x03 \x01(\t\x12\x0b\n\x03sig\x18\x04 \x01(\t\x12\x15\n\rfilename_base\x18\x05 \x01(\t\"\x9f\x02\n\x14\x46\x65tchCrashesResponse\x12\x43\n\x05state\x18\x01 \x01(\x0e\x32\x34.test_platform.phosphorus.FetchCrashesResponse.State\x12\x37\n\x07\x63rashes\x18\x02 \x03(\x0b\x32&.test_platform.phosphorus.CrashSummary\x12\x18\n\x10\x63rashes_rtd_only\x18\x04 \x03(\t\x12\x18\n\x10\x63rashes_tls_only\x18\x05 \x03(\t\"U\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\r\n\tSUCCEEDED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\r\n\tTIMED_OUT\x10\x03\x12\x0b\n\x07\x41\x42ORTED\x10\x04\x42\x44ZBgo.chromium.org/chromiumos/infra/proto/go/test_platform/phosphorusb\x06proto3')



_FETCHCRASHESREQUEST = DESCRIPTOR.message_types_by_name['FetchCrashesRequest']
_CRASHSUMMARY = DESCRIPTOR.message_types_by_name['CrashSummary']
_FETCHCRASHESRESPONSE = DESCRIPTOR.message_types_by_name['FetchCrashesResponse']
_FETCHCRASHESRESPONSE_STATE = _FETCHCRASHESRESPONSE.enum_types_by_name['State']
FetchCrashesRequest = _reflection.GeneratedProtocolMessageType('FetchCrashesRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHCRASHESREQUEST,
  '__module__' : 'test_platform.phosphorus.fetchcrashes_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.phosphorus.FetchCrashesRequest)
  })
_sym_db.RegisterMessage(FetchCrashesRequest)

CrashSummary = _reflection.GeneratedProtocolMessageType('CrashSummary', (_message.Message,), {
  'DESCRIPTOR' : _CRASHSUMMARY,
  '__module__' : 'test_platform.phosphorus.fetchcrashes_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.phosphorus.CrashSummary)
  })
_sym_db.RegisterMessage(CrashSummary)

FetchCrashesResponse = _reflection.GeneratedProtocolMessageType('FetchCrashesResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHCRASHESRESPONSE,
  '__module__' : 'test_platform.phosphorus.fetchcrashes_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.phosphorus.FetchCrashesResponse)
  })
_sym_db.RegisterMessage(FetchCrashesResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZBgo.chromium.org/chromiumos/infra/proto/go/test_platform/phosphorus'
  _FETCHCRASHESREQUEST.fields_by_name['use_staging']._options = None
  _FETCHCRASHESREQUEST.fields_by_name['use_staging']._serialized_options = b'\030\001'
  _FETCHCRASHESREQUEST._serialized_start=146
  _FETCHCRASHESREQUEST._serialized_end=334
  _CRASHSUMMARY._serialized_start=336
  _CRASHSUMMARY._serialized_end=463
  _FETCHCRASHESRESPONSE._serialized_start=466
  _FETCHCRASHESRESPONSE._serialized_end=753
  _FETCHCRASHESRESPONSE_STATE._serialized_start=668
  _FETCHCRASHESRESPONSE_STATE._serialized_end=753
# @@protoc_insertion_point(module_scope)
